### PR TITLE
Fixed scroll down when active section is last resolve #87

### LINKED ISSUE #87: scroll error on macbook trackpad
the scroll error occurs when on the alvarotrigo site http://alvarotrigo.com/pagePiling/ I scroll down on my macbook trackpad to the fourth page and then attempt to scroll again - it takes me back to the third page, and then to the fourth http://jmp.sh/oOKku7C
I was unable to reproduce this here: http://www.alvarotrigo.com/fullPage/#secondPage
this also occurs occaisonally on the third (final) page without scrolling again
you scroll 1 then 2 then 3, then pause as if to read the third slide, but it goes back to the second slide

### PR DESCRIPTION
**Pull request by rpelczar**

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Can you add more information about what does if fixes, how to reproduce it or in which conditions it takes place?

**Comment by RooFi07** [comment]
Yes, when you scroll down, method moveSectionDown checks whether the next section exists, if not, it does nothing and doing it over and over again. At the very end, when slow, delta equals the 0 and scrolls up.

**Comment by alvarotrigo** [comment]
What browser and OS are you using to get a 0 value of delta? 
Are you using a mouse or a trackpad?

I'm quite surprised you can get a zero value there. [fullPage.js](http://alvarotrigo.com/fullPage/) is using the same implementation to get the delta value and nobody complained about a similar issue.

I've tested [this jsfiddle](https://jsfiddle.net/nwvnmhck/) in Firefox, Chrome and IE and none of them return 0 to me when using a mouse wheel.

**Comment by RooFi07** [comment]
I use osx and trackpad. When I tested [this jsfiddle](https://jsfiddle.net/nwvnmhck/) in Firefox it was good, but when I used Chrome at the end accelerate scroll console.log return -0.

fullPage.js work me too.

**Comment by alvarotrigo** [comment]
> fullPage.js work me too.

You mean, you don't get the error there?

**Comment by alvarotrigo** [comment]
> at the end accelerate scroll console.log return -0.

You mean, in the last section? Or accelerating after a normal scroll .

**Comment by RooFi07** [comment]
> You mean, you don't get the error there?
Yes, it's ok.

> You mean, in the last section? Or accelerating after a normal scroll .
The osx scroll on the trackpad accelerates and slows down. The last point scroll the delta value is -0.

**Comment by alvarotrigo** [comment]
Ok I'll take a look from home later.

**Pull request closed without merging**
